### ISSUE TITLE
connection.metadata properties should be snake_case

### ISSUE THREAD

**Issue by joshbax189** [Meeco/js-sdk#79]
The generated properties connection.metadata.fromName, fromEmail etc. violate the snake_case convention used for API properties. Docs: https://github.com/Meeco/js-sdk/tree/master/packages/cli#connection

**Comment by zbarbuto** [comment]
I agree - this is worth making consistent.

Sharing and connections work has been put on-hold temporarily for internal reasons but when we start to look at it again this is definitely worth changing 👍
